if weight1 + weight2 = 2.0 and bias= -1.1, difference is about 0.9 (ignoring the negative sign). so adjust the weights in a way the difference is as small as 0.9, you can also toy with the negative sign, by placing it beside weight 1 or 2 or bias or 1&bias or 1&2 or 2&bias, you get the gist, right. Apply theory as intuition leads

In [14]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 1.0
weight2 = 1.0
bias = -1.1


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

Input 1    Input 2    Linear Combination    Activation Output   Is Correct
      0          0                  -1.1                    0          Yes
      0          1                  -0.1                    0          Yes
      1          0                  -0.1                    0          Yes
      1          1                   0.9                    1          Yes


---

What are two ways to go from an AND perceptron to an OR perceptron?

Increase the weights && Decrease the magnitude of the bias

---

 calculate the NOT operation on the second input and ignores the first input

In [50]:
import pandas as pd

# TODO: Set weight1, weight2, and bias
weight1 = 1.0
weight2 = -2.0
bias = .5


# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]
outputs = []

# Generate and check output
for test_input, correct_output in zip(test_inputs, correct_outputs):
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    output = int(linear_combination >= 0)
    is_correct_string = 'Yes' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Linear Combination', '  Activation Output', '  Is Correct'])
if not num_wrong:
    print('Nice!  You got it all correct.\n')
else:
    print('You got {} wrong.  Keep trying!\n'.format(num_wrong))
print(output_frame.to_string(index=False))

Nice!  You got it all correct.

Input 1    Input 2    Linear Combination    Activation Output   Is Correct
      0          0                   0.5                    1          Yes
      0          1                  -1.5                    0          Yes
      1          0                   1.5                    1          Yes
      1          1                  -0.5                    0          Yes


$$w_1x_1 + w_2x_2 + b = 0$$

For `test_input=(0,0)`

$$weight_1 = 0$$
$$weight_1 = -2$$
$$bias = 0.5$$
$$x_1 = 0$$
$$x_2 = 0$$

$$0*0 + -2*0 + 0.5 = .5$$

### Percepton Implementation

#### Rf. 14.9, in which they graph the boundary lines

In [70]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(len(X)):
        y_hat = prediction(X[i], W, b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
            print(W[0], W[1], b)
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
            print(W[0], W[1], b)
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines


In [76]:
data = np.asarray(pd.read_csv('data_percepton.csv', header=None))

In [82]:
x_data = data[:,0:2]
y_data =data[:,2]


In [84]:
trainPerceptronAlgorithm(x_data, y_data, learn_rate = 0.01, num_epochs = 25)

[0.05255061] [0.85617615] 1.5911150117432087
[0.04812321] [0.85025565] 1.5811150117432087
[0.03960561] [0.84364365] 1.5711150117432087
[0.03356201] [0.83498315] 1.5611150117432087
[0.02673771] [0.83015305] 1.5511150117432086
[0.01673771] [0.82247155] 1.5411150117432086
[0.00943881] [0.81436455] 1.5311150117432086
[0.00270111] [0.80656705] 1.5211150117432086
[-0.00517499] [0.80074935] 1.5111150117432086
[-0.01231919] [0.79308135] 1.5011150117432086
[-0.01725709] [0.78765875] 1.4911150117432086
[-0.02515449] [0.78023545] 1.4811150117432086
[-0.03194499] [0.77414335] 1.4711150117432086
[-0.03858699] [0.76689145] 1.4611150117432086
[-0.04652659] [0.76121255] 1.4511150117432086
[-0.05360239] [0.75361035] 1.4411150117432086
[-0.05954449] [0.74742465] 1.4311150117432085
[-0.06448089] [0.74180225] 1.4211150117432085
[-0.07225159] [0.73829975] 1.4111150117432085
[-0.08023009] [0.73060765] 1.4011150117432085
[-0.08731769] [0.72093125] 1.3911150117432085
[-0.09423529] [0.71484475] 1.3811150117432

[-0.59977529] [-0.16122047] 0.41111501174320764
[-0.59432259] [-0.15482937] 0.42111501174320765
[-0.59874999] [-0.16074987] 0.41111501174320764
[-0.60368789] [-0.16617247] 0.40111501174320763
[-0.60862429] [-0.17179487] 0.3911150117432076
[-0.61320719] [-0.17643587] 0.3811150117432076
[-0.61766279] [-0.18223497] 0.3711150117432076
[-0.60985769] [-0.18287166] 0.3811150117432076
[-0.60489389] [-0.17833326] 0.3911150117432076
[-0.59790319] [-0.17460256] 0.40111501174320763
[-0.59119539] [-0.16994876] 0.41111501174320764
[-0.58574269] [-0.16355766] 0.42111501174320765
[-0.59017009] [-0.16947816] 0.41111501174320764
[-0.59510799] [-0.17490076] 0.40111501174320763
[-0.60004439] [-0.18052316] 0.3911150117432076
[-0.60462729] [-0.18516416] 0.3811150117432076
[-0.60908289] [-0.19096326] 0.3711150117432076
[-0.60127779] [-0.19159995] 0.3811150117432076
[-0.59631399] [-0.18706155] 0.3911150117432076
[-0.58932329] [-0.18333085] 0.40111501174320763
[-0.58261549] [-0.17867705] 0.41111501174320764
[-

[(array([0.55152414]), array([-2.13117352])),
 (array([3.75673789]), array([-3.59593078])),
 (array([55.12356555]), array([-27.42299077])),
 (array([-49.0767963]), array([22.27866742])),
 (array([-24.32584137]), array([11.5513429])),
 (array([-17.55313]), array([8.42633519])),
 (array([-13.66461999]), array([6.63213149])),
 (array([-12.24363032]), array([6.22133349])),
 (array([-10.39943233]), array([5.34801072])),
 (array([-9.0092606]), array([4.68969277])),
 (array([-7.92382577]), array([4.17568345])),
 (array([-7.05282428]), array([3.76321937])),
 (array([-6.33842492]), array([3.42491446])),
 (array([-5.74187677]), array([3.14241817])),
 (array([-5.23623986]), array([2.90297304])),
 (array([-4.80220388]), array([2.69743464])),
 (array([-4.42556584]), array([2.51907712])),
 (array([-4.12305068]), array([2.37817856])),
 (array([-3.85258389]), array([2.25220675])),
 (array([-3.60932889]), array([2.13890902])),
 (array([-3.38937567]), array([2.03646426])),
 (array([-3.1895291]), array([